"""add transit schedule indexes

Revision ID: 212a6adc0faa
Revises: b47735aaf6c8
Create Date: 2026-09-30 19:27:20.921104

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "212a6adc0faa"
down_revision: str | Sequence[str] | None = "b47735aaf6c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_stop_times_stop_id"),
        "stop_times",
        ["stop_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stop_times_trip_id"),
        "stop_times",
        ["trip_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_trips_route_unique_id"),
        "trips",
        ["route_unique_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_trips_route_unique_id"),
        table_name="trips",
    )
    op.drop_index(
        op.f("ix_stop_times_trip_id"),
        table_name="stop_times",
    )
    op.drop_index(
        op.f("ix_stop_times_stop_id"),
        table_name="stop_times",
    )
    # ### end Alembic commands ###
