"""create stops table

Revision ID: 594092046904
Revises:
Create Date: 2026-09-29 21:58:31.392039

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "594092046904"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
                spatial_index=False,
            ),
            nullable=False,
        ),
        sa.Column("direction", sa.String(length=10), nullable=True),
        sa.Column("direction_id", sa.Integer(), nullable=True),
        sa.Column("opposite_stop_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["opposite_stop_id"],
            ["stops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_stops_location",
        "stops",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_stops_location", table_name="stops", postgresql_using="gist")
    op.drop_table("stops")
    # ### end Alembic commands ###
