"""create vehicle position history

Revision ID: a8a8c62fe18d
Revises: 212a6adc0faa
Create Date: 2026-10-01 17:53:05.456954

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8a8c62fe18d"
down_revision: str | Sequence[str] | None = "212a6adc0faa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_positions",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "vehicle_number",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "trip_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "vehicle_trip_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_vehicle_positions_recorded_at",
        "vehicle_positions",
        ["recorded_at"],
        unique=False,
    )

    op.create_index(
        "ix_vehicle_positions_vehicle_recorded_at",
        "vehicle_positions",
        ["vehicle_number", "recorded_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_vehicle_positions_vehicle_recorded_at",
        table_name="vehicle_positions",
    )

    op.drop_index(
        "ix_vehicle_positions_recorded_at",
        table_name="vehicle_positions",
    )

    op.drop_table("vehicle_positions")
    # ### end Alembic commands ###
