"""create transit schedule tables

Revision ID: b47735aaf6c8
Revises: 594092046904
Create Date: 2026-09-30 19:13:43.853336

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b47735aaf6c8"
down_revision: str | Sequence[str] | None = "594092046904"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routes",
        sa.Column("unique_id", sa.String(length=50), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("route_number", sa.String(length=50), nullable=False),
        sa.Column("direction_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=255), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("unique_id"),
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_unique_id", sa.String(length=50), nullable=False),
        sa.Column("vehicle_trip_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_unique_id"],
            ["routes.unique_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stop_times",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("stop_id", sa.Integer(), nullable=False),
        sa.Column("arrival_time", sa.DateTime(), nullable=True),
        sa.Column("departure_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stop_id"],
            ["stops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stop_times")
    op.drop_table("trips")
    op.drop_table("routes")
    # ### end Alembic commands ###
